### ISSUE TITLE
readme: add coordinates to maven artifacts

### ISSUE THREAD

**Issue by hastebrot** [netopyr/reduxfx#17]
The `README.md` could have a reference to the Maven artifacts. The shields badge automatically refers to the current version. I've also added snippets of other common ways to refer to the artifacts, which require to manually update the version string on every release.

**As shields badge:**

~~~md
[![Maven](https://img.shields.io/maven-central/v/com.netopyr.reduxfx/reduxfx.svg?label=com.netopyr.reduxfx)](https://search.maven.org/#search|ga|1|com.netopyr.reduxfx)
~~~

[![Maven](https://img.shields.io/maven-central/v/com.netopyr.reduxfx/reduxfx.svg?label=com.netopyr.reduxfx)](https://search.maven.org/#search|ga|1|com.netopyr.reduxfx)

**As maven coordinates table:**

~~~md
| Group ID            | Artifact ID | Version |
| :-----------------: | :---------: | :-----: |
| com.netopyr.reduxfx | reduxfx     | 0.1.0   |
~~~

| Group ID            | Artifact ID | Version |
| :-----------------: | :---------: | :-----: |
| com.netopyr.reduxfx | reduxfx     | 0.1.0   |

**For maven pom xml:**

~~~xml
<dependencies>
    <dependency>
        <groupId>com.netopyr.reduxfx</groupId>
        <artifactId>reduxfx</artifactId>
        <version>0.1.0</version>
    </dependency>
</dependencies>
~~~

**For gradle build file:**

~~~groovy
dependencies {
    compile "com.netopyr.reduxfx:reduxfx:0.1.0"
}
~~~

**As maven repository index url:**

- http://central.maven.org/maven2/com/netopyr/reduxfx/reduxfx/
- https://mvnrepository.com/artifact/com.netopyr.reduxfx/reduxfx
- https://search.maven.org/#search|ga|1|com.netopyr.reduxfx

**Comment by netopyr** [comment]
Thanks a lot! You are absolutely right, this information belongs into the README.md
