### ISSUE TITLE
add selection to ListView

### ISSUE THREAD

**Issue by manuel-mauky** [netopyr/reduxfx#52]
At the moment the VNode ListView doesn't support selection of items (at least I haven't seen the possibility to do so). 
This includes 2 aspects: I like to be able to define which items are selected based on the state and I like to dispatch an action when the user selects an item.

I've tried to add this functionality and to provide a PullRequest but I haven't understood how to add this with the existing builders. I think the reason is that the selection is not just a property on the ListView but instead in normal JavaFX you have to use the `SelectionModel` from the ListView. 

If you can give me some hints on how this should be implemented I'm happy to provide a PullRequest.

**Comment by netopyr** [comment]
That is really a good question I have not thought about until now. Have you ever used a custom implementation of SelectionModel? So far I have only used the default ones and it is not clear to me in which cases a custom implementation is needed.

I think there are two possibilities how this could be implemented. The SelectionModel could be mapped to a special, distinct node in the VirtualScenegraph. The usage would be slightly more complicated, but one could provide custom implementations of SelectionModel.

The other option would be to flatten the API and move the required properties directly into ListViewBuilder. This would be simpler to use, but it would prevent custom implementations.

Right now I do not know what the right approach would be. Option 2 would be sufficient for me, though it would certainly be a limitation compared to the JavaFX API.

**Comment by manuel-mauky** [comment]
I have also thought about Option 2. I don't use custom SelectionModels and I don't know any use cases either. I would ignore this until someone has an actual use case for custom selection models. 

I would be happy with a flattened API for selection. Most methods of the SelectionModel is imperative API like `select(T obj)` or `clearSelection()` which we don't need for reduxfx anyway.
